### ISSUE TITLE
does this support authentik?

### ISSUE THREAD

**Issue by kundeng** [stefanwerfling/flyingfish#88]
Thanks!

**Comment by stefanwerfling** [comment]
Hello @kundeng I just looked at authentik, the “[Reverse proxy](https://docs.goauthentik.io/docs/install-config/reverse-proxy)” part briefly explains which settings need to be made. This would automatically be approved by FlyingFish with a certificate. The “X-Forwarded” headers would all be set, and you can also activate the wake-up socket in the UI. Make sure the destination is port 9443. 

Since I can't authenticate beforehand, I can't say anything else about the installation.


You are welcome to contact me at any time!

**Comment by kundeng** [comment]
I haven't really used flyingfish. I'm using nginx proxy manager as someone made a video about how it or traefik can work with forward-auth mode of authentik.

**Comment by stefanwerfling** [comment]
That was a good hint with "forward-auth mode". I just found the documentation for this (https://docs.goauthentik.io/docs/add-secure-apps/providers/proxy/server_nginx)

This isn't rocket science in itself, I wanted to provide templates (header redirects and defaults) in later versions anyway. Right now I would have to come up with something else for version 1.1.13. We could offer a list of headers on the route that you can maintain yourself or something like that.

What do you think about it? Would such a list be understandable? 

I'm thinking about it again too. You have to know that Nginx is 100% configured programmatically. I had set myself the goal that no one would enter incorrect configs, which in turn is done in the Nginx Proxy Manager.

**Comment by kundeng** [comment]
Thanks for the hint! Yeah, I've been avoiding diving too deep into nginx syntax myself—it's like opening Pandora's box, right? 😅 The setup you're suggesting with a manageable header list on routes sounds like it could simplify things and keep the user experience straightforward, especially for those of us who aren’t trying to master every aspect of nginx just to get a system up and running.

I'm all for the idea of templates and defaults in future versions. A configurable list of headers would be a good step forward for now—seems like a practical approach that could prevent misconfigurations while keeping things flexible. If you’re aiming to keep nginx setups transparent and user-friendly, this could be the way to go. 

Thanks for your work on this.
